In [4]:
#импорт numpy
import numpy as np

#массив из списка
data = [1,2,3]
array_from_list = np.array(data)
print(array_from_list)

#массив с помощью zeros
zeros_array = np.zeros(3)
print(zeros_array)

#массив с помощью ones
ones_array = np.ones((3, 3))
print(ones_array)

#массив с помощью arange
range_array = np.arange(0, 10, 2)  #от 0 до 10 с шагом 2
print(range_array)

#атрибуты на примере ones_array
print(ones_array.shape)
print(ones_array.dtype)
print(ones_array.ndim)

#Примеры индексирования и срезов
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

#получение отдельного элемента
element = matrix[1, 2]
print(element)

#извлечение подмассива с помощью среза
submatrix = matrix[0:2, 1:3]
print(submatrix)

# Векторные операции
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

#сложение
print(arr1 + arr2)

#умножение
print(arr1 * arr2)

#вычисление статистик
print(np.mean(arr1))
print(np.sum(arr2))
print(np.max(arr1))
print(np.min(arr2))

[1 2 3]
[0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
(3, 3)
float64
2
[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[2 3]
 [5 6]]
[11 22 33 44 55]
[ 10  40  90 160 250]
3.0
150
5
10
